spring:
  application:
    name: reviewer

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/reviewer

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/reviewer
    username: reviewer
    password: reviewer

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  liquibase:
    enabled: false
    change-log: classpath:db/changelog/changelog-master.xml
    parameters:
      spring.datasource.password: reviewer

  springdoc:
    api-docs:
      path: /api-docs
