version: '3.8'

services:
  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: reviewer
      POSTGRES_USER: reviewer
      POSTGRES_PASSWORD: reviewer
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U reviewer -d reviewer" ]
      interval: 10s
      retries: 5
      start_period: 10s

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8088:8080"

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    restart: unless-stopped
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: reviewer
      KC_DB_USERNAME: reviewer
      KC_DB_PASSWORD: reviewer
    command: ["start-dev", "--log-level=DEBUG"]
    ports:
      - "8081:8080"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
    driver: local
