services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: reviewer
      POSTGRES_USER: reviewer
      POSTGRES_PASSWORD: reviewer
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8088:8080

volumes:
  postgres_data:
    driver: local